image: node:6.5.0
cache:
  paths:
  - node_modules/

before_script:
  - npm cache clean
  - bower --allow-root cache clean
  - rm -rf node_modules bower_components dist tmp
  - npm install
  - bower --allow-root install

production:
  type: deploy
  script:
  - apt-get update -qy
  - echo "Y" |apt-get install libssl-dev
  - apt-get install -y rubygems
  - gem install dpl
  - dpl --provider=heroku --app=leituradebolsogestor-prod --api-key=$HEROKU_PRODUCTION_API_KEY

  only:
  - master

stagging:
  type: deploy
  script:
  - apt-get update -qy
  - echo "Y" |apt-get install libssl-dev
  - apt-get install -y rubygems
  - gem install dpl
  - dpl --provider=heroku --app=leituradebolsogestor --api-key=$HEROKU_PRODUCTION_API_KEY

  only:
  - dev
